#!/bin/bash
echo "CI_Startup Script started"
echo "Waiting for all other server startup processes to finish: 15 seconds"
sleep 15

# MaNGOS realmd authentication server startup
echo "Starting Realmd --> Account Server"
/bin/su mangos -c "/usr/bin/screen -dmS realm_d bash -c '/opt/mangos3_ci_server/bin/realmd'"

# MaNGOS world server
echo "Starting Mangosd --> World Server"
/bin/su mangos -c "/usr/bin/screen -dmS mangos_d bash -c '/opt/mangos3_ci_server/bin/mangosd'"

#screen daemon for eth0 Network traffic monitoring
echo "slurm_eth0 network monitor daemon"
/bin/su morketh -c "/usr/bin/screen -dmS slurm bash -c 'slurm -I eth0'"

#screen daemon TeamSpeak3
echo "Starting Teamspeak 3"
/bin/su zaine -c "/usr/bin/screen -dmS TeamSpeak3 bash -c '/opt/teamspeak3-server_linux-x86/teamspeak_startscript.sh start'"
